"use strict";
Object.defineProperty(exports, "__esModule", { value: true });
/* tslint:disable */
require('./RecentFilesTab.module.css');
var styles = {
    filePicker: 'filePicker_7bc814ab',
    tabsContainer: 'tabsContainer_7bc814ab',
    tabContainer: 'tabContainer_7bc814ab',
    nav: 'nav_7bc814ab',
    tabHeaderContainer: 'tabHeaderContainer_7bc814ab',
    breadcrumbNav: 'breadcrumbNav_7bc814ab',
    breadcrumbNavItem: 'breadcrumbNavItem_7bc814ab',
    tab: 'tab_7bc814ab',
    tabFiles: 'tabFiles_7bc814ab',
    scrollablePaneWrapper: 'scrollablePaneWrapper_7bc814ab',
    actionButtonsContainer: 'actionButtonsContainer_7bc814ab',
    actionButtons: 'actionButtons_7bc814ab',
    actionButton: 'actionButton_7bc814ab',
    tabHeader: 'tabHeader_7bc814ab',
    selectedTab: 'selectedTab_7bc814ab',
    header: 'header_7bc814ab',
    xlg: 'xlg_7bc814ab',
    xxlg: 'xxlg_7bc814ab',
    xxxlg: 'xxxlg_7bc814ab',
    xxxxlg: 'xxxxlg_7bc814ab',
    itemPickerTopBar: 'itemPickerTopBar_7bc814ab',
    commandBarNoChevron: 'commandBarNoChevron_7bc814ab',
    fileItem: 'fileItem_7bc814ab',
    folderItem: 'folderItem_7bc814ab',
    fileTypeIcon: 'fileTypeIcon_7bc814ab',
    fileTypeIconIcon: 'fileTypeIconIcon_7bc814ab',
    detailsListHeaderFileTypeIcon: 'detailsListHeaderFileTypeIcon_7bc814ab',
    iconColumnHeader: 'iconColumnHeader_7bc814ab',
    fileRow: 'fileRow_7bc814ab',
    folderRow: 'folderRow_7bc814ab',
    emptyFolder: 'emptyFolder_7bc814ab',
    emptyFolderImage: 'emptyFolderImage_7bc814ab',
    emptyFolderImageTag: 'emptyFolderImageTag_7bc814ab',
    emptyFolderTitle: 'emptyFolderTitle_7bc814ab',
    emptyFolderSubText: 'emptyFolderSubText_7bc814ab',
    emptyFolderMobile: 'emptyFolderMobile_7bc814ab',
    emptyFolderPc: 'emptyFolderPc_7bc814ab',
    emptyFolderIcon: 'emptyFolderIcon_7bc814ab',
    gridListCell: 'gridListCell_7bc814ab',
    cellRight: 'cellRight_7bc814ab',
    cellLastRow: 'cellLastRow_7bc814ab',
    itemTile: 'itemTile_7bc814ab',
    isFile: 'isFile_7bc814ab',
    isPhoto: 'isPhoto_7bc814ab',
    isVideo: 'isVideo_7bc814ab',
    hasThumbnail: 'hasThumbnail_7bc814ab',
    itemTileContent: 'itemTileContent_7bc814ab',
    itemTileDiscoverFileContainer: 'itemTileDiscoverFileContainer_7bc814ab',
    itemTileFileContainer: 'itemTileFileContainer_7bc814ab',
    itemTileFile: 'itemTileFile_7bc814ab',
    itemTileThumbnail: 'itemTileThumbnail_7bc814ab',
    image: 'image_7bc814ab',
    itemTileCheckCircle: 'itemTileCheckCircle_7bc814ab',
    isSelected: 'isSelected_7bc814ab',
    itemTileNamePlate: 'itemTileNamePlate_7bc814ab',
    itemTileName: 'itemTileName_7bc814ab',
    itemTileChildCount: 'itemTileChildCount_7bc814ab',
    itemTileSubText: 'itemTileSubText_7bc814ab',
    recentGridList: 'recentGridList_7bc814ab',
};
exports.default = styles;
/* tslint:enable */ 

//# sourceMappingURL=RecentFilesTab.module.scss.js.map
